### ISSUE TITLE
Logo for HackForValley

### ISSUE THREAD

**Issue by Yashank18** [HackForValley/Flutter-App#1]
Please send your entries here in the comments to this thread.

**Comment by anshuman725** [comment]
![logo](https://user-images.githubusercontent.com/57260235/80910886-38ea4a00-8d50-11ea-8e05-ab730c824362.png)

**Comment by anshuman725** [comment]
![logo](https://user-images.githubusercontent.com/57260235/80910943-a0a09500-8d50-11ea-84d0-6a996a43ac33.png)

**Comment by Yashank18** [comment]
@anshuman725 I like the second one but add something related to code here. 
In first the background color isn't that appealing

**Comment by vivekgugnani** [comment]
![Screenshot (471)](https://user-images.githubusercontent.com/56130227/80912755-dcd9f280-8d5c-11ea-86bc-e9c65992c228.png)

**Comment by ishandeveloper** [comment]
![hack_for_valley](https://user-images.githubusercontent.com/54989142/80913552-072eae80-8d63-11ea-932f-085cd2d85d79.png)

**Comment by anshuman725** [comment]
![logo](https://user-images.githubusercontent.com/57260235/80914838-e61e8b80-8d6b-11ea-8e46-ab27edc450ef.jpg)

**Comment by anshuman725** [comment]
![Screenshot (261)](https://user-images.githubusercontent.com/57260235/80914900-401f5100-8d6c-11ea-8bf4-87fa6d217a2d.png)

**Comment by anshuman725** [comment]
![Screenshot (262)](https://user-images.githubusercontent.com/57260235/80915318-3814e080-8d6f-11ea-9fdb-0fbe73bb4d6a.png)

**Comment by Mayank0022** [comment]
![HackForValley](https://user-images.githubusercontent.com/57790631/80917182-f38f4200-8d7a-11ea-815f-63c8076283c3.jpg)

**Comment by Charu271** [comment]
![Screenshot (218)](https://user-images.githubusercontent.com/60181628/80917461-a8762e80-8d7c-11ea-8508-d90ae4ea847c.png)

**Comment by vivekgugnani** [comment]
![Screenshot (472)](https://user-images.githubusercontent.com/56130227/80936321-4eae4c80-8dee-11ea-8a73-56f38d673f20.png)

**Comment by satvikchachra** [comment]
Experimenting :
<details>
<summary>Option A</summary>
<img src="https://user-images.githubusercontent.com/50296407/80947692-50880800-8e0e-11ea-8c89-e42c1a56eae2.png">
</details>

<details>
<summary>Option B</summary>
<img src="https://user-images.githubusercontent.com/50296407/80947429-ccce1b80-8e0d-11ea-9230-6f4bade33cde.png">
</details>

<details>
<summary>Option C</summary>
<img src = "https://user-images.githubusercontent.com/50296407/80947433-cdff4880-8e0d-11ea-9bfe-912e6e55a539.png">
</details>

<details>
<summary>Option D</summary>
<img src = "https://user-images.githubusercontent.com/50296407/80947435-ce97df00-8e0d-11ea-91fb-427cffe36079.png">
</details>

**Comment by Yashank18** [comment]
@ishandeveloper @anshuman725 @Charu271 @Vivek0004 
Good Idea guys but thinking about using the logo with transparent background, I feel like option C of @satvikchachra looks fine. Please share your views @AnmolSehgal @goyalmuskan @SaranshDawra

**Comment by SaranshDawra** [comment]
> @ishandeveloper @anshuman725 @Charu271 @Vivek0004
> Good Idea guys but thinking about using the logo with transparent background, I feel like option C of @satvikchachra looks fine. Please share your views @AnmolSehgal @goyalmuskan @SaranshDawra

Yes, Option C looks fine.

**Comment by goyalmuskan** [comment]
> @ishandeveloper @anshuman725 @Charu271 @Vivek0004
> Good Idea guys but thinking about using the logo with transparent background, I feel like option C of @satvikchachra looks fine. Please share your views @AnmolSehgal @goyalmuskan @SaranshDawra

Yes, Option C looks good.
