### ISSUE TITLE
UI designs for login/sign up page and homepage

### ISSUE THREAD

**Issue by Yashank18** [HackForValley/Flutter-App#3]
Should use a material design theme. 
Comment here and will assign it to the one with the best design to create a PR.

**Comment by Mayank-create** [comment]
i would like to work on it

**Comment by ishandeveloper** [comment]
### Here's A Quick Mockup !
@Yashank18 

<img src="https://user-images.githubusercontent.com/54989142/81494714-98080b80-92c8-11ea-8b96-6d4263c184a0.gif" height="500em">

#### 🎨 Color Palette : #3146F0, #69A1AC, #444444 
##### Will share the rest of the assets later 😃

**Comment by Yashank18** [comment]
Great work @ishandeveloper

**Comment by sidharathjain2** [comment]
@Yashank18 
![hackfinal1](https://user-images.githubusercontent.com/63875151/81500528-59864700-92f0-11ea-8572-8113cbb9a5d1.png)
![hackfinal2](https://user-images.githubusercontent.com/63875151/81500534-67d46300-92f0-11ea-9028-d2c5724d4a57.png)
![hackfinal3](https://user-images.githubusercontent.com/63875151/81500541-6c991700-92f0-11ea-8e4e-5af1b43039d3.png)
![hackfinal4](https://user-images.githubusercontent.com/63875151/81500544-73278e80-92f0-11ea-921c-0145aa5b3232.png)

**Comment by Yashank18** [comment]
@sidharathjain2 good work

**Comment by Yashank18** [comment]
@ishandeveloper Make a Pr with a text file containing screenshots of the proposed UI  and all the required information. Closing this issue.
